
class ForbiddenModuleUseInValidator(ImportError): ...

class SchemaLoadingException(Exception): ...

class IncorrectFieldTypeError(ValueError): ...

class FieldValidationErrorInfo:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __init__(self) -> None: ...
